name: "OpenSprinkler by Sdomotica"
description: "OpenSprinkler Firmware custom for BTicino SCS"
version: "2025.5.6"
slug: "opensprinkler_sdomotica"
arch:
  - aarch64
init: false
options: {}
schema: {}
# Disattiviamo Ingress per usare il link diretto sulla porta esterna
ingress: false
webui: "http://[HOST]:[PORT:8080]"
panel: true
panel_icon: "mdi:sprinkler-variant"
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiomem:/dev/gpiomem
  - /dev/gpiochip0:/dev/gpiochip0
  - /dev/gpiochip1:/dev/gpiochip1
  - /dev/gpiochip2:/dev/gpiochip2
  - /dev/gpiochip3:/dev/gpiochip3
  - /dev/gpiochip4:/dev/gpiochip4
ports:
  8080/tcp: 5557
ports_description:
  8080/tcp: Web interface
dependencies:
  - core_mosquitto