name: "OpenSprinkler by Sdomotica"
description: "OpenSprinkler Firmware custom for BTicino SCS"
version: "2026.6.1"
slug: "opensprinkler_sdomotica"
arch:
  - aarch64
init: false
options: {}
schema: {}
# Abilita l'interfaccia protetta e integrata
ingress: true
ingress_port: 8080
# Forza la creazione del pannello laterale nativo per Ingress
panel: true
panel_icon: "mdi:sprinkler-variant"
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiomem:/dev/gpiomem
  - /dev/gpiochip0:/dev/gpiochip0
  - /dev/gpiochip1:/dev/gpiochip1
  - /dev/gpiochip2:/dev/gpiochip2
  - /dev/gpiochip3:/dev/gpiochip3
  - /dev/gpiochip4:/dev/gpiochip4
ports:
  8080/tcp: 5557
ports_description:
  8080/tcp: Web interface
dependencies:
  - core_mosquitto
  
map:
  - data:rw
  - share:rw
  - config:rw
  