FROM sdomotica/sdomotica:first
#-- Logs and config information go into the volume on /data
VOLUME /sdomotica

#-- OpenSprinkler interface is available on 8080
EXPOSE 3100 3000 3300

CMD [ "./sdomotica/sdomotica" ]
